# Target library
lib := libuthread.a
objs := queue.o
CC := gcc
CFLAGS:= -Wall -Wextra -Werror -MMD
CFLAGS += -g

ifneq($(V), 1)
Q = @
endif

all: $(lib)

## TODO: Phase 1
deps := $(patsubst %.o, %.d, $(objs))
-include $(deps)

libuthread.a: $(objs)
	@echo "CC $@"
	$(Q)$(CC) $(CFLAGS) -o $@ $^

%.o: %.c
	@echo "CC $@"
	$(Q)$(CC) $(CFLAGS) -c -o $@ $<

clean:
	@echo "CC $@"
	$(Q)rm -f $(lib) $(objs) $(deps)
